development:
  adapter: mysql2
  encoding: utf8mb4
  database: potatos_dev
  username: root
  password:
  host: localhost
  pool: 5

test:
  adapter: mysql2
  encoding: utf8mb4
  database: potatos_test
  username: root
  password:
  host: localhost
  pool: 5

production:
  adapter: mysql2
  encoding: utf8mb4
  database: potatos_prod
  username: root
  password:
  host: localhost
  pool: 5
